import type { Metadata } from "next";
import "./globals.css";
import { Krub } from "next/font/google";
import Footer from "@/components/Shared/Footer";
import Header from "@/components/Shared/Header";

export const krub = Krub({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-krub",
});

export const metadata: Metadata = {
  title: "ShopTonAlternance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${krub.variable}`}>
      <body>
        <div className="sticky top-4 mt-4 w-full z-50">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
